### ISSUE TITLE
Add breadcrumb in /doc/essays/*

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1049]
For example, see this page
https://www.python.org/doc/essays/pepparade/

It will be nice if there's a breadcrumb on top that will take us back to https://www.python.org/doc/essays/

:)

As a comparison, the page https://www.python.org/community/diversity/ has a breadcrumb on top.

**Comment by berkerpeksag** [comment]
Breadcrumbs are created automatically by django-sitetree. https://www.python.org/community/diversity/  has a breadcrumb because it's part of the site tree. Unfortunately there is no relation between pages (our `Page` model) and site tree so a page must be added to the site tree manually. Since these essay are here for historical reasons, I don't think they are important enough to do this manual work (also this might have performance impact because even now sitetree is a bit slow especially in admin -- #1048 might help to improve the current situation)

I've added a "Python Essays" item to the site tree since it's a bit hard to find them on the site and it has a breadcrumb now (only on the essay index page) Thank you for the report.
