### ISSUE TITLE
ftp resource for exercising in cpython integration tests

### ISSUE THREAD

**Issue by orsenthil** [python/pythondotorg#1069]
We currently don't have a ftp resource at python.org that we can utilize for exercising "ftp" integration. I was planning to use
```ftp://ftp.debian.org/debian/README```, but I thought, it will be better point a resource hosted at python.org

**Comment by berkerpeksag** [comment]
This looks like a good case to use https://github.com/python/pythontestdotnet instead of python.org.

**Comment by orsenthil** [comment]
Sure, I agree.  I thought, even for creating a resource under pythontest.net I had to create a ticket somewhere. Is this a right place? Or should I send an email to infra team? (FWIW, I am willing to help to setup the resource too).

**Comment by berkerpeksag** [comment]
We used bugs.python.org before since the main use case of pythontest.net is CPython's test suite. I'd say either use bugs.p.o. or email to infrastructure@p.o :)

By the way, I'm not familiar with FTP protocol, but is it possible to create a local FTP server when running the test suite like we do for netrc and other tests?

**Comment by berkerpeksag** [comment]
We can also use http://bugs.python.org/issue22650 to discuss this.

**Comment by ammaraskar** [comment]
This can now be closed, there is now an ftp server running on pythontest.net along with a PR out to change the ftp tests to use it.
