### ISSUE TITLE
Would like "IBM i" added to "Python for Other platforms" page

### ISSUE THREAD

**Issue by ThePrez** [python/pythondotorg#1072]
Proposed changes to this page:   https://www.python.org/download/other/

1) Add a section "Python for IBM i", with the following text:
"Both Python 2.7 and Python 3.4 are available for free for IBM i via the 5733OPS licensed program offering. For more information about 5733OPS, see the offering's landing page on [IBM developerWorks](https://ibm.co/2jgNvhY). 
Alternatively, http://www.iseriespython.com hosts an IBM i port of Python 2.7, ported by Per Gummedal. "

2) Remove the "Python for AS/400" section ("AS/400" is the name of a platform predecessor, now outdated by well over a decade)

I'd happily submit  pull request with the changes, but can't find where they'd be made. 

Thank you!

**Comment by jkyeung** [comment]
While I know that virtually everyone *within* the IBM midrange community knows that the term "AS/400" is outdated, I personally prefer to reach as many people as possible. Relevant points:

* I suspect that among people *outside* the IBM midrange community, the term "AS/400" is actually more recognizable than "IBM i".
* Notice all the other legacy platforms listed on that page. Just because they are outdated doesn't mean they aren't still usable and in use. And worth mentioning on that page.
* iSeriesPython *is* usable on the AS/400. I know someone who was using it in production on a V4R-something system, and our i still has production Python code that was developed on V5R2. The latest available incarnation of iSeriesPython runs on everything from V5R3 and up.

So what am I proposing? I don't think there should be two (or more) separate sections for the different names. I think one is good. See "Python for OS/390 and z/OS".

I have to admit I kinda liked being listed first on the page, but I would be OK with giving up that spot in an effort to be more current. I think it would be best if we somehow showcase that IBM i is the current name, but also include a nod to its predecessors. That is, "Python for IBM i (older names go in parens here)". And this is where it gets tricky, because outsiders who have heard the term "AS/400" generally think of that as both the hardware and operating system. But the convention on that page is to list operating systems (thus the current listing shows both "AS/400" because it's recognizable, and "OS/400" because it's the OS name).

And once that issue is decided, it probably makes sense to note that IBM's 5733OPS stuff is only available for 7.1 and up, while iSeriesPython goes back to *at least* V5R3 (but is also usable on the latest IBM i). (Perhaps not mentioning precise versions, but at least somehow indicating the difference in coverage.)

Sorry, I don't have time to think through all this stuff fully right at the moment, but I wanted to at least bring up these issues so others could mull them over and weigh in.

**Comment by ThePrez** [comment]
@jkyeung, thanks for opening this discussion. I understand your concerns completely

Here is a revised proposal. 
Section title: "Python for IBM i (formerly AS/400, iSeries, System i)"
"Both Python 2.7 and Python 3.4 are available for free for IBM i via the 5733OPS licensed program offering. These binaries require IBM i 7.1 or newer. For more information about 5733OPS, see [the offering's landing page on IBM developerWorks](https://ibm.co/2jgNvhY).
Alternatively, http://www.iseriespython.com hosts an IBM i port of Python 2.7, ported by Per Gummedal, which can also be run on older versions of the operating system."

Thoughts?

**Comment by jkyeung** [comment]
I like the revised proposal. Unfortunately, I don't know where to make the change (as a pull request) either. I am actually the one who asked them to update the entry to what it is now, back in March 2014. At that time, I used the general Python tracker (bugs.python.org, to report it as a "documentation bug"). They made the change, but asked me to report future python.org site issues here instead. And now we're here. So I don't know how we get things moving from this point.

**Comment by ThePrez** [comment]
Thanks, @jkyeung! I think the next action here is for @berkerpeksag, so I'll patiently wait for him. :)

**Comment by berkerpeksag** [comment]
@ThePrez is right, I'll do the suggested changes this week :) Thank you!

**Comment by berkerpeksag** [comment]
Done. Please check https://www.python.org/download/other/ again. I have used the suggested text in https://github.com/python/pythondotorg/issues/1072#issuecomment-301512387 and sorted the list in alphabetical order.

Thank you for the report, @ThePrez and thank you for the feedback, @jkyeung.
