### ISSUE TITLE
Remove Python Dev Firefox Search Plugin page

### ISSUE THREAD

**Issue by DimitrisJim** [python/pythondotorg#1076]
The image is missing, the link is broken and I can't seem to find the plugin on firefox. Is there any benefit to keeping [the page](https://www.python.org/dev/searchplugin/) around?

**Comment by berkerpeksag** [comment]
Looks like the page wasn't converted correctly when we switched to the current site. Since `addEngine()` is not defined and modern browsers have built-in support for this use case, I don't see a reason to keep this page on python.org.

I unpublished the page now. We can republish and update its content if we want in the future.

Thank you for the report!
