### ISSUE TITLE
Python Package List linked within Python website is depracate. Yet, it is still listed there.

### ISSUE THREAD

**Issue by AprilMorone** [python/pythondotorg#1101]

**Comment by berkerpeksag** [comment]
Thank you for the report. Could you also share the full URL of the page you saw "Python Package List" with us?

**Comment by berkerpeksag** [comment]
Looking at this again, I think the OP is talking about https://pypi.python.org/pypi/ I couldn't find any link to it on www.python.org (note the `www.` part) so I assume the OP was asking why it's still listed on legacy PyPI. PyPI maintainers can't just delete a page without explaining the reasoning so that's why they kept the page and all links to it.

Anyway, this tracker is for issues with www.python.org. Please use https://github.com/pypa/pypi-legacy if you have further questions, thank you!
