### ISSUE TITLE
Python 1.6.1 downloads give 404 (legacy.python.org)

### ISSUE THREAD

**Issue by AndrewSav** [python/pythondotorg#1143]
This page https://www.python.org/download/releases/1.6.1/download/ used to link to download archive of Python 1 at legacy.python.org

Just recently this (and windows exe) link became broken, given 404 when clicked.

Where Python 1 can be downloaded now?

**Comment by berkerpeksag** [comment]
Apparently, http://legacy.python.org/ is no longer available. @MarkMangoba is there a problem with legacy.p.o or is it intentionally closed?

**Comment by MarkMangoba** [comment]
@berkerpeksag should be back up, some configuration issue but now resolved.

**Comment by berkerpeksag** [comment]
@MarkMangoba thank you for the quick fix! I can confirm that Python 1.6.1 can now be downloaded. Thank you for the report, @AndrewSav.

**Comment by AndrewSav** [comment]
Thank you for looking into this! @MarkMangoba @berkerpeksag Out of curiosity  https://www.python.org/ftp/python/ contains releases 'til 1.5 and starting from 2.0, but not 1.6.1 I was wondering why it's setup this way?

**Comment by berkerpeksag** [comment]
I think 1.6.1 is special case because of a license change. If I remember correctly, it's basically the same release as 1.6.0 but its license was changed to a GPL-compatible license and people needed to explicitly accept it before downloading the source code.

Note that I was in middle school at the time so I might be wrong :)
