### ISSUE TITLE
Impossible download python 3.6.2 and 2.7 documentation (html)

### ISSUE THREAD

**Issue by disatoba** [python/pythondotorg#1148]
Hi, 

Links to python 3.6.2 and 2.7 documentation in HTML are broken, web server returns 404 Not Found.

The links are:
https://docs.python.org/2/archives/python-2.7.14rc1-docs-html.zip
https://docs.python.org/3/archives/python-3.6.2-docs-html.zip

Is there other way to download it?, Many thanks in advance, ​

Best regards,

**Comment by Mariatta** [comment]
Thanks for the report. Issues with Python documentation can be filed in https://bugs.python.org. It is out of the scope of this tracker.

**Comment by berkerpeksag** [comment]
An issue was opened at bugs.p.o: https://bugs.python.org/issue31395 Ned just opened https://github.com/python/psf-salt/issues/118 to track down this problem.

**Comment by mwichmann** [comment]
This isn't terribly helpful: this is closed pointing to bugs.python.org, and the bug there is closed pointing back here.  While bunches of people are running into this problem (there have been several emails to webmaster), at least one bug "for normal people" (by which I mean not psf-salt, whatever that is) should stay open to show what's happening, since it's a real problem they're seeing.

**Comment by n8henrie** [comment]
@mwichmann Looks like the active issue is: https://github.com/python/psf-salt/issues/118

As noted [here](https://bugs.python.org/msg301978), the release version is still available for download:

- Not working: https://docs.python.org/3/archives/python-3.6.2-docs-html.zip
- Working: https://docs.python.org/ftp/python/doc/3.6.2/python-3.6.2-docs-html.zip
