### ISSUE TITLE
Login problems on bugs.python.org

### ISSUE THREAD

**Issue by embray** [python/pythondotorg#1223]
Sorry if this is the wrong place for bugs.python.org issues--I couldn't find anything else obvious.

I use the Google-based OID login for bpo, and have for a very long time.  But right now when I try to log in it just hangs for a very long time, and then displays an error message: "There is already an account for `<my gmail address>`".  But I'm not trying to create an account, just log into my existing one. 

To be clear, this is through https://bugs.python.org/index?@action=oic_login&provider=Google

**Comment by berkerpeksag** [comment]
There is a link to http://psf.upfronthosting.co.za/roundup/meta/ in the sidebar of bugs.python.org. Unfortunately, we can't help you for issues with bugs.p.o. You can also ping Taggnostr or bitdancer on #python-dev on Freenode.

If I remember correctly, I got the same message when I tried to login with my Google account last year. I was able to login by using the "lost your account?" link and by using my username and password instead of my Google account.
