### ISSUE TITLE
python.org outage:  Apr 30, 2018 - 16:41 UTC

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#1249]
https://status.python.org/incidents/ttdz2bj310xw

@ewdurbin reported:  "something is endlessly retrying to call to legacy.pypi.org, this was causing a timeout uwsgi was aggressively killing"

**Comment by ewdurbin** [comment]
The issue here appears to be that urls/domains in blog.python.org post titles or bodies are attempted to be resolved/accessed in some manner.

The string `legacy.pypi.org` was included in a blog title/post this morning announcing the shutdown of... well `legacy.pypi.org`.

As a result when the blog update management command ran, the index page render times ground to a halt. Based on an `strace` this was endlessly retrying calls to `legacy.pypi.org`:

<img width="762" alt="screen shot 2018-04-30 at 1 33 37 pm" src="https://user-images.githubusercontent.com/1200832/39444092-810bdd8a-4c84-11e8-993e-aacc3ca7a1cf.png">

**Comment by berkerpeksag** [comment]
Can I use https://blog.python.org/2018/04/new-pypi-launched-legacy-pypi-shutting.html to write a test case/reproduce the problem locally or is there a way to see the content of the original post?

**Comment by ewdurbin** [comment]
@berkerpeksag I took the original post that was causing trouble down from blog.python.org... I'm not sure the best way to give you a reproduction case.

**Comment by berkerpeksag** [comment]
@ewdurbin I can probably tweak the management command to import data from a file (or something similar) if you send me the title and the body of the original post via email or IRC.

**Comment by ewdurbin** [comment]
https://gist.github.com/ewdurbin/7902bd2e3ddd696926ecd52aeff8a87f

**Comment by berkerpeksag** [comment]
Here's what I did to try to reproduce this:

1. Created a blog and a post: https://eddiesmemories.blogspot.com.tr/2018/05/legacypypiorg-shut-down-please-use.html
2. Created a FeedBurner feed: http://feeds.feedburner.com/EddiesMemories
3. Added the feed I created in step 2 via Django admin
4. Ran `./manage.py update_blogs` and it completed successfully:

    ![screenshot from 2018-05-01 17 47 55](https://user-images.githubusercontent.com/26338/39477352-b8ee4d1c-4d67-11e8-8a37-8b921ddaa2bf.png)

The only place that makes an HTTP request is https://github.com/python/pythondotorg/blob/acae696a22d76fbda64bf046c311a408f6af605d/blogs/parser.py#L13

`feedparser.parse()` uses the old `urllib.request.build_opener()` interface and it doesn't set a default value for timeout (which means it will wait indefinitely) The feedparser module doesn't provide a way to set a timeout value so I will update that function to fetch `feed_url` via `requests` and then pass the response to `feedparser.parse()`.

**Comment by scottilee** [comment]
@berkerpeksag can this be closed?

**Comment by hugovk** [comment]
Yes, six years later I think it's time to close this.
