### ISSUE TITLE
unbelievable little bug in 3.6.4 & 3.6.5

### ISSUE THREAD

**Issue by xcray** [python/pythondotorg#1298]
```print(2.3*0.65)```
very simple, the result should be 1.495, but python3 said the result is 1.4949999999.
it's ok in 2.7.10

interesting?

**Comment by berkerpeksag** [comment]
1. This issue tracker is for issues with www.python.org, the official website of Python, not about Python usage.
2. You see that result because of IEEE 754. See https://docs.python.org/3/tutorial/floatingpoint.html for more details. Also, Python version shouldn't matter because both major versions (Python 2.x and Python 3.x) are IEEE 754 compliant:

   ```
   $ python
   Python 2.7.3 (default, Oct 26 2016, 21:01:49) 
   [GCC 4.6.3] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   >>> 2.3*0.65
   1.4949999999999999


   $ python3.4
   Python 3.4.3+ (3.4:c7b9645a6f35, May 23 2015, 02:12:44) 
   [GCC 4.6.3] on linux
   Type "help", "copyright", "credits" or "license" for more information.
   >>> 2.3*0.65
   1.4949999999999999
   ```

**Comment by xcray** [comment]
so there is difference on print() function between 2.x and 3.x
anyhow, this is not the place for this topic.
thanks~
