### ISSUE TITLE
Link to PSF fellow member rosters from PSF Fellow nomination page

### ISSUE THREAD

**Issue by Mariatta** [python/pythondotorg#1324]
It would be nice if we can provide link to the PSF roster membership page (https://www.python.org/psf/members/#id5) from the PSF fellow nomination page. (https://www.python.org/psf/fellows/)

The PSF fellow nomination page only lists fellows inducted in the last 12 months it seems.

I think having a full list in there will be useful for people to see who have been or have not been recognized as a PSF fellow. Without the full list, there is possibility for potential fellow to be overlooked because they were assumed to already been a fellow. Having that link handy will be useful.

Thanks.

**Comment by berkerpeksag** [comment]
Agreed. Last time I wanted to nominate someone I decided to do it later because I didn't know if the person has already been recognized as a fellow or received a community service award.

I've added the following sentence:

> You can see the full list of fellows at the PSF Membership Roster page.

Feel free to suggest a different wording or a better place to put the link to the list of fellows.
