### ISSUE TITLE
Your account menu error in mobile

### ISSUE THREAD

**Issue by Adarshreddyash** [python/pythondotorg#1339]
It is refreshing when we click on your account menu

**Comment by berkerpeksag** [comment]
Can you try to reproduce this on staging.python.org? Also, giving more information about your device, operating system, and browser would help us to track down the issue. Thanks!

**Comment by bhawesh96** [comment]
I tried to reproduce the error on staging.python.org using dev-tools to check behaviour on a phone.

### Bug:
Page refreshes on clicking 'Your account'

### Expected behaviour: 
Dropdown menu should open and show options under 'Your account'

Dropdown is visible on clicking 'Socialise' but page refreshes on clicking 'Your account'
![screenshot from 2018-10-03 16-13-01](https://user-images.githubusercontent.com/17593065/46405918-6bbcfe00-c727-11e8-853a-e4e69d46512c.png)


@berkerpeksag I am new to open source and would like to fix this issue.

**Comment by Adarshreddyash** [comment]
@bhawesh96 this is the actual problem

**Comment by bhawesh96** [comment]
@berkerpeksag If you've approved this issue, can I work on it?

**Comment by Adarshreddyash** [comment]
@berkerpeksag even i can help you

**Comment by Mariatta** [comment]
Thanks for the report! I confirmed this is still a problem in staging.python.org. I used Chrome browser on my Android phone.

Please propose a PR if you can.

**Comment by Adarshreddyash** [comment]
Solved
