### ISSUE TITLE
Add link to bitbucket.org

### ISSUE THREAD

**Issue by akuchling** [python/pythondotorg#135]
CPython development is done using Mercurial, so we should link to Bitbucket as well as Github.  

Is there an official team to link to?  There's https://bitbucket.org/PSF, but I don't know if that's official or was just used for the site redesign.

**Comment by benjaminp** [comment]
hg.python.org might be more appropiate

**Comment by brettcannon** [comment]
I say we drop the GitHub link rather than add a bitbucket one. If you look at bitbucket's CPython mirror it is behind by a few days (while the GitHub mirror is behind by hours).

But the code locations really don't have any social aspects to them as the other things in that list of links and so they seem out of place.

**Comment by birkenfeld** [comment]
> I say we drop the GitHub link rather than add a bitbucket one.

Agreed.
