### ISSUE TITLE
Windows x86 & 64 MSI installers for latest Python Releases

### ISSUE THREAD

**Issue by telatoa** [python/pythondotorg#1382]
**Is your feature request related to a problem? Please describe.**
This request is related to the following issue: [https://github.com/crossbario/crossbar/issues/1479](url)

We use **Crossbar** that is now only supported with **Python >= 3 version**.

Our InstallShield project needs to use the **MSI** version of Python and it seems that the latest Python version that has an **MSI** version is **2.7**.

**Describe the solution you'd like**
To have **Windows x86 & 64 MSI installers** for latest Python Releases (**3.7.2**).

**Comment by mwichmann** [comment]
The decision on WIndows installers comes from the Python team, it is not a website issue - that is, you need to pursue it at https://bugs.python.org.  MSI installers have not been produced since the 3.4 series. The situation is described here: http://stevedower.id.au/blog/why-so-many-python-installers/

**Comment by ewdurbin** [comment]
Closing unless @zooba has any additional considerations.
