### ISSUE TITLE
File Operation is not working in python

### ISSUE THREAD

**Issue by ferozkhan674** [python/pythondotorg#1396]
Hi, 
I'm using python 3.7.2 latest version on Mac OS Mojave Version number 10.14.3.
Problem here is while using File operation in using above python version, it's saying that file not found Error. 

Command I used here is 
fo=open("go.txt","r") 

However, in my friend laptop OS Windows 8.1, Python version 3.7.1, the same command is accept sometime and sometime not.. 

Kindly, fix this issue...

**Comment by Mariatta** [comment]
This issue tracker is for python.org website, not for CPython itself.

If you believe there is a bug with CPython, it can be filed at https://bugs.python.org, and it will be helpful if you provide as much details as you can, such as exactly which error message was shown, steps to reproduce, and so on. If Python says file does not exists, perhaps it is correct, and maybe you need to supply full path to the file, instead of "go.txt".
