### ISSUE TITLE
Download Page Not Appearing Correctly

### ISSUE THREAD

**Issue by rzscheck** [python/pythondotorg#1420]
The download page appears as raw text. A note at the top says I don't have JavaScript enabled but I do. Using the latest Google Chrome. The main page looks normal.

**Comment by aayush420** [comment]
> The developer console says that it is missing a css stylesheet. Look like there is an issue with the build setup. The missing stylesheet is https://www.python.org/static/stylesheets/style.67f4b30f7483.css
Looks like the page is still referring the old stylesheet which has been updated on 10th April. The new stylesheet is **style.3dbbbf7ee488.css** while it is still referring the old one **style.67f4b30f7483.css**. <br /><br/>Magically, the stylesheet was present on 10th April and disappeared since then. The Internet archive has recorded the stylesheet and is available at http://web.archive.org/web/20190410234936cs_/https://www.python.org/static/stylesheets/style.67f4b30f7483.css. Notice the timestamp that says 2019-04-10 23:49:36.
<br />
<br />

![image](https://user-images.githubusercontent.com/16898783/56089111-837df780-5eab-11e9-8e4a-b6049679ae8e.png)

![image](https://user-images.githubusercontent.com/16898783/56089260-b0cba500-5ead-11e9-8dce-8095a7daf156.png)

**Comment by adamchainz** [comment]
Seeing this too

**Comment by berkerpeksag** [comment]
It should be fixed now. Thank you for the reports!

I will file another issue to investigate how to invalidate Fastly cache (not every page, of course!) after a successful deployment.

**Comment by adamchainz** [comment]
Working, thanks!
