### ISSUE TITLE
v3.5 problems (documentation)

### ISSUE THREAD

**Issue by SadAleix** [python/pythondotorg#1449]
**Describe the bug**
The roblem is - that i can't change versions of Python in documentation, if i choose v3.5

**To Reproduce**
1. Go to 'any link in "docs.python.org"'
2. Click on 'version'
3. Click on '3.5'

**Expected behavior**
I expected, that i can change switch to another version

**Screenshots**
![image](https://user-images.githubusercontent.com/50663670/58777502-038d2780-85e8-11e9-8d09-40d796aa448c.png)
![image](https://user-images.githubusercontent.com/50663670/58777524-1b64ab80-85e8-11e9-938d-53292288e47d.png)
![image](https://user-images.githubusercontent.com/50663670/58777536-261f4080-85e8-11e9-81dc-3e883dbb7724.png)

**Desktop (please complete the following information):**
 - OS: [windows 7, 64 bit]
 - Browser [chrome]
 - Version [74.0.3729.169 ]

**Smartphone (please complete the following information):**
 - Device: [Meizu pro 6s]
 - OS: [android 6.0]
 - Browser [chrome]
 - Version [74.0.3729.157]

**Comment by berkerpeksag** [comment]
Thank you for your report!

1) The correct place to report issues with docs.p.o is bugs.python.org (or you can send an email to docs@python.org)

2) Version switcher is only enabled for active branches (3.6, 3.7, 3.8 (not yet created), and master (3.9)) 3.5 is now in security-fix-only mode, so we no longer build `Doc/` directory from the 3.5 branch. The reason why the version switcher is disabled in security-fix-only branches is that because there's no way to update list of versions (e.g. adding 3.9 or 3.10 to the version list) once we stopped building them daily (i.e. you won't be able to go 3.9 docs from 3.5 docs)
