### ISSUE TITLE
Incomplete installation of 3.8.0 on MacOS

### ISSUE THREAD

**Issue by leahymr** [python/pythondotorg#1534]
I just installed Python 5.8.0 on my MacOS 10.14.6 system.  I'm not sure that pip installed properly.

`[Veritas:~] leahym$ python3 --version`
Python 3.8.0
`[Veritas:~] leahym$ which python3`
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3
`[Veritas:~] leahym$ which pip`
/Library/Frameworks/Python.framework/Versions/3.7/bin/pip
`[Veritas:~] leahym$ which pip3`
/Library/Frameworks/Python.framework/Versions/3.8/bin/pip3

Shouldn't it have created a pip executable or link that connects to pip3?

Thanks,
--Michael

**Comment by ned-deily** [comment]
Thanks for the report but this issue tracker is for issues with the python.org website, not with use of Python of Python-related packages.

I will note that there are long-standing problems with `pip` versus `pip3`; see, for example, https://bugs.python.org/issue33290, https://github.com/pypa/pip/issues/6444, and https://github.com/pypa/pip/issues/3164.  This kind of problem can arise when using pip to update itself.  To avoid such confusion, the current best practice recommendation is to use `python3 -m pip` instead of `pip3` to invoke `pip`; that ensures that you are using the version of pip associated with the `python3` you are using.

**Comment by leahymr** [comment]
Thank you, Ned,

But I think you misunderstood my issue.

I did a fresh install of Python 3.8 on MacOS (using the .DMG file).  The installer placed pip3 and pip3.8 in my Python bin directory, but it did not create an file for pip.

The Python 3.7.4 installer *did* create that file for me.

[Veritas:/Library/Frameworks/Python.framework/Versions/3.7/bin] leahym$ ls -lFi
total 128  
3816890 lrwxr-xr-x  1 root    admin     8 Sep 24 08:51 2to3@ -> 2to3-3.7
3816891 -rwxrwxr-x  1 root    admin   140 Jul  8 14:55 2to3-3.7*
4891061 -rwxr-xr-x  1 leahym  admin   277 Oct 31 19:32 easy_install*
4891062 -rwxr-xr-x  1 leahym  admin   277 Oct 31 19:32 easy_install-3.7*
3816892 lrwxr-xr-x  1 root    admin     7 Sep 24 08:51 idle3@ -> idle3.7
3816893 -rwxrwxr-x  1 root    admin   138 Jul  8 14:55 idle3.7*
4707887 -rwxr-xr-x  1 leahym  admin   267 Oct 20 14:04 pip*
4707888 -rwxr-xr-x  1 leahym  admin   267 Oct 20 14:04 pip3*
4707889 -rwxr-xr-x  1 leahym  admin   267 Oct 20 14:04 pip3.7*
3816894 lrwxr-xr-x  1 root    admin     8 Sep 24 08:51 pydoc3@ -> pydoc3.7
3816895 -rwxrwxr-x  1 root    admin   123 Jul  8 14:55 pydoc3.7*
3816896 lrwxr-xr-x  1 root    admin     9 Sep 24 08:51 python3@ -> python3.7
3816897 lrwxr-xr-x  1 root    admin    16 Sep 24 08:51 python3-config@ -> python3.7-config
3816898 -rwxrwxr-x  2 root    admin  9604 Jul  8 14:55 python3.7*
3816899 lrwxr-xr-x  1 root    admin    17 Sep 24 08:51 python3.7-config@ -> python3.7m-config
3816898 -rwxrwxr-x  2 root    admin  9604 Jul  8 14:55 python3.7m*
3816902 -rwxrwxr-x  1 root    admin  1974 Jul  8 14:55 python3.7m-config*
3816903 lrwxr-xr-x  1 root    admin    10 Sep 24 08:51 pyvenv@ -> pyvenv-3.7
3816904 -rwxrwxr-x  1 root    admin   480 Jul  8 14:55 pyvenv-3.7*

[Veritas:/Library/Frameworks/Python.framework/Versions/3.8/bin] leahym$ ls -lFi
total 80
5380678 lrwxr-xr-x  1 root  admin     8 Nov 18 13:01 2to3@ -> 2to3-3.8
5380679 -rwxrwxr-x  1 root  admin   140 Oct 14 10:24 2to3-3.8*
5389540 -rwxrwxr-x  1 root  admin   280 Nov 18 13:01 easy_install-3.8*
5380680 lrwxr-xr-x  1 root  admin     7 Nov 18 13:01 idle3@ -> idle3.8
5380681 -rwxrwxr-x  1 root  admin   138 Oct 14 10:24 idle3.8*
5390665 -rwxrwxr-x  1 root  admin   262 Nov 18 13:01 pip3*
5390666 -rwxrwxr-x  1 root  admin   262 Nov 18 13:01 pip3.8*
5380682 lrwxr-xr-x  1 root  admin     8 Nov 18 13:01 pydoc3@ -> pydoc3.8
5380683 -rwxrwxr-x  1 root  admin   123 Oct 14 10:24 pydoc3.8*
5380684 lrwxr-xr-x  1 root  admin     9 Nov 18 13:01 python3@ -> python3.8
5380685 lrwxr-xr-x  1 root  admin    16 Nov 18 13:01 python3-config@ -> python3.8-config
5380686 -rwxrwxr-x  1 root  admin  9604 Oct 14 10:23 python3.8*
5380687 -rwxrwxr-x  1 root  admin  2172 Oct 14 10:24 python3.8-config*


It is entirely possible that the development team (or the packaging team) decided to stop including ‘pip’ in the distribution, since I see that all the executables are now *3 or *3.8, and ‘pip’ was the only file that wasn’t named that way.  But since there was no announcement in the Release Notes, I couldn’t tell if that was an intentional omission or an accident.

I updated my copy of pip3 after I submitted my bug report… but thanks for the warning about using the pip3 tool.

Thanks,
—Michael

**Comment by ned-deily** [comment]
It's a confusing issue, I'll admit, but "The Python 3.7.4 installer *did* create that file for me" is not correct.  If you look at the dates and user names in your 3.7 directory, it appears you last installed python3.7 on Sep 24 because that is the date of all the *3 symlinks which are created when the installer runs.  But pip, pip3, and pip37 are dated Oct 20 and with your user name, not root.  So it's highly likely on Oct 20 you updated pip in 3.7.  And *that's* when the incorrect ``pip`` file was created as described in the issues I cited above.  There never should have been a ``pip`` in a system-wide Python 3 bin directory.  There remains some controversy about this but, in general, the rule is there should only be a ``pip`` if there is also a ``python`` in the same bin directory; likewise, ``pip3`` -> ``python3``, etc.  Virtual environments muddy the water here because they create both a `python` and `python3` in the virtual environment `bin` directory so there having  both a `pip` and a `pip3` is consistent - kinda.  Again, this is why it's best to avoid the problem by invoking `pip` via `python* -m` which works for all current versions of Python, including Python 2.7, and whether you are using a virtual environment or not.

**Comment by leahymr** [comment]
Ah, thank you for clarifying.  Sorry for the inconvenience.

—Michael
