### ISSUE TITLE
Can't locate files to download 3.6.10 for Windows

### ISSUE THREAD

**Issue by MidniteA** [python/pythondotorg#1563]
I'm looking for the latest security updates to the 3.6.x series of Python for Windows (to use with our Adobe Sync Tool product that we've had for about 6 months, which still recommends this Python version https://helpx.adobe.com/enterprise/using/user-sync.html).

When on the Python.org website I keep getting led back to version 3.6.10, but the only files available for download aren't for Windows.  This is the link I keep ending up at:
https://www.python.org/downloads/release/python-3610/
and when I'm searching for Windows versions this page does include 3.6.10: https://www.python.org/downloads/windows/

I've tried reading the latest update information/release notes here: https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-10-final 
to see if Windows maybe just isn't included with these security updates but it's not clear to me if that is what the issue is (and I'm new Python and keeping it updated).

I'm also including a screen capture of what I can see for downloads on the 3.6.10 page.
![Python Files](https://user-images.githubusercontent.com/61834281/75986010-1d72d800-5ea2-11ea-965e-2f768cf10fb3.PNG)

Thank you for any help or guidance you can provide!

**Comment by ned-deily** [comment]
The information about Python 3.6.x releases is contained in the [Python 3.6 Release PEP ](https://www.python.org/dev/peps/pep-0494/)which is linked to on the release page.  Granted the relevant info may not leap out at you especially if you are new to Python releases, but what it says there is that Python 3.6.8 in 2018-12 was the last **bugfix** release of the Python 3.6.x release series; that means it is the last 3.6.x release for which we provide binary installers for Windows and macOS.  Any subsequent releases, like 3.6.10, are called **security** fixes; they are released as needed and generally contain only fixes for important security problems. **Security** fix releases are intended for users supporting themselves on older versions of Python and as such we do not provide binary installers for such releases.  We move older releases from **bugfix** to **security** release mode after a suitable overlap period when a new version of Python is released.  As of now, Python 3.8.x is the most current version of Python in **bugfix** mode and should be the version of choice for new usage.  (Python 3.7.x is also now in **bugfix** mode but will itself be entering **security** mode in a few months.)  Suggest you contact Adobe and ask them for an update. If you feel adventurous, you *might* also try using their tool with Python 3.8.x; it *might* just work OK.  We strongly discourage using obsolete binary releases, like installing an older version of 3.6.x, as you would be vulnerable to bugs and security issues that have been fixed in newer releases.
