### ISSUE TITLE
found a virus with python2.7 in python.org

### ISSUE THREAD

**Issue by selvaganesh123** [python/pythondotorg#1573]
**Describe the bug**
Someone has uploaded or binded a virus with python 2.7 in https://www.python.org/ftp/python/2.7/python-2.7.msi

**To Reproduce**
1. Go to 'https://www.python.org/ftp/python/2.7/python-2.7.msi'
2. Go to 'downloads'
3.Scan for virus

**Expected behavior**
download and install.

**Screenshots**
![Screenshot (123)](https://user-images.githubusercontent.com/36336261/79065150-a5cb7080-7ccb-11ea-954e-eec8a3355488.png)

**Desktop (please complete the following information):**
 - OS: Windows 8 pro
 - Browser: chrome
 - Version: 80.0.3987.163 (Official Build) (32-bit)

**Additional context**
please check the file that was hosted

**Comment by hugovk** [comment]
No problem when scanning with F-Secure on macOS, nor with these online scanners:

* https://opentip.kaspersky.com/FC446293CC61CC5D60E81021ABA8C3AA55ED688E929E23EA240512B91DEE462F/

* https://www.virustotal.com/gui/file-analysis/MTcxOWZlYmNiYzBlMGFmM2E2ZDNhNDdiYTVmYmY4NTE6MTU4NzM5OTU4Mg==/detection

What antivirus program and version are you using?

**Comment by ned-deily** [comment]
Note that the file in question is for the original release of Python 2.7 from the year 2010, in other words, 10 years old!  The most recent release of Python 2.7 was 2.7.18, a few weeks ago, which is also the final release of 2.7.x; it is now in end-of-life status.  As far as I can tell, the installer file has not been modified in ten years so, if the published checksums and GPG signatures of the copy you downloaded match, it is almost certainly a false positive in the virus checker you are using (this is not an uncommon occurrence).  In any case, unless you are interested in some historical research in running a ten-year-old-version of Python 2.7 (without the subsequent 18 releases-worth of fixes for numerous bugs, security issues, and updates to run on current operating system releases), you should be using the most current 2.7, if you absolutely need to stay with Python 2, otherwise you should consider [downloading and using a current supported version of Python 3](https://www.python.org/downloads/) (currently 3.8.2).
