### ISSUE TITLE
Hello everyone, I am making an exe file from python(.py) using pyinstaller. The code requires connection to SQL database through cx_Oracle. Exe file gets crated successfully and runs on my PC properly. However, when I share it with a team member of mine, it does not run on some other PC and gives this error: "cannot open self abc or archive abc.pkg" (abc being the name of exe). It would be very nice if someone could help on the same. 

### ISSUE THREAD

**Issue by Shaggun45** [python/pythondotorg#1604]

**Comment by Mariatta** [comment]
This issue tracker is for issues related to Python dot org website, not for questions about using Python. You can probably ask those questions in forums like stack overflow or python-list mailing list.

Also, in the future, it would be great if you could post to post a short and concise issue title, and leave the long details in the description instead of in the subject. Thanks.
