### ISSUE TITLE
Work on removing links to the wiki

### ISSUE THREAD

**Issue by akuchling** [python/pythondotorg#161]
We should try to remove links that go into the wiki, replacing them with new pages or with a specialized micro-site (something like http://www.getpython3.com).

Rationales (feel free to debate!): the wiki page design looks completely different, and there's no easy way to get back to www.python.org.  The user-editability of the wiki is not much of a benefit, because there's little activity; the modern way to achieve the same result is to fork the micro-site's repository on Github and make edits, which could be done completely within the Github web interface.

Things that could be moved to micro-sites: the list of Python books, the Beginner's Guide.

(This would be a large task.)

**Comment by malemburg** [comment]
This may work out for some pages, but certainly not in general. There are several wiki pages which are edited regularly and giving all users write access to www.python.org doesn't sound like a good solution to me. It would also introduce a security risk, since we'd hardly be able to monitor every single change on the site's pages (even less so, since Django doesn't send email notifications for page changes).

A much better solution would be to add the www.python.org styles to the Python wiki, IMO. These could then also provide links back to the main site.

**Comment by ShalokShalom** [comment]
The python wiki is outdated and unmainted, yes?
IT leads users into confusing situations and since most people prefer official pages, is this imho a large issue. Take it down. Make it clean. Anything, which works. :)

**Comment by malemburg** [comment]
The Python wiki is not unmaintained. We're getting new editor requests quite frequently.

Unlike the python.org website, the wiki does allow community involvement and so provides the necessary means to allow for improvement. We do need more people working on the content. Feel free to sign up as wiki editor:

https://wiki.python.org/moin/FrontPage#use

As mentioned before, it would also be helpful to have the wiki better integrate into the python.org website. Patches with wiki theme adjustments are welcome.

**Comment by ShalokShalom** [comment]
Just because you get editor requests, make that the python wiki not automatic maintained.

**Comment by hugovk** [comment]
Let's close this: there are some useful pages on the wiki that are maintained.

Other wiki pages can be edited and improved, or their links removed from here. But let's evaluate them on a case-by-case basis.
