### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by GordonRaleigh** [python/pythondotorg#1628]
**Description of the Issue**
503 Service Unavailable Error in the Python interactive shell, at https://www.python.org/shell/

**Steps to Replicate**
1. Go to https://www.python.org/shell/
2. Notice the error message inside the shell

**System Information**
OS: Windows 10 Home
Browser: Firefox
Version: 79

![503](https://user-images.githubusercontent.com/70111146/90986999-84ba3c80-e555-11ea-9aa0-de6fb3fc5fa2.PNG)

**Comment by hugovk** [comment]
The shell is an iframe of https://console.python.org/python-dot-org-console/

Which is meant to be a proxy to PythonAnywhere: https://github.com/python/pythondotorg/pull/482

**Comment by berkerpeksag** [comment]
Thank you for the report. As Hugo said, the service is provided by PythonAnywhere so I'll just ping @gpjt in case this is specific to our instance.

**Comment by gpjt** [comment]
Thanks!  Coincidentally I spotted that earlier on today and dropped a line to the infrastructure-staff list asking them to take a look.  The 503 error is indeed coming from a python.org server that is reverse-proxying stuff down to us. 

It's possible that it's giving that error because we're blocking traffic from it -- we have had a bunch of DDoS attacks recently, and perhaps our mitigation scripts got a false-positive and blocked it.  If you let us know the IP address that we would see from our server when the proxy connects to us, we can check it out and whitelist it if necessary.

**Comment by GordonRaleigh** [comment]
@gpjt Are you asking for my public IP address to see if it needs to be whitelisted?

**Comment by gpjt** [comment]
@GordonRaleigh -- no, it's the IP address that the server console.python.org uses for its downstream requests.

**Comment by gpjt** [comment]
The infrastructure team have provided us with the IP we needed, and now it's whitelisted -- consoles are back up and running :-)

**Comment by berkerpeksag** [comment]
Thank you!
