### ISSUE TITLE
string concatenation via `sum`

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [python/pythondotorg#1632]
I'm not sure whether this is a bug or a feature request, but it seems as though the following should produce the same result:

In [1]: 'a' + 'b' + 'c'
Out[1]: 'abc'

In [2]: sum(('a', 'b', 'c'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-56f085fe45f2> in <module>
----> 1 sum(('a', 'b', 'c'))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

The error message is confusing (there is no integer).

**Comment by hugovk** [comment]
This is the repository and issue tracker for the https://www.python.org website.

If you're looking to file an issue with CPython itself, please go to https://bugs.python.org

**Comment by ghost** [comment]
Hey dear
Try storing the string into a variable first and then try to add them...
This might help you 
Thanks ;)

**Comment by ghost** [comment]
But if it still not works then I think that the sum () function can only add integers and floats

**Comment by berkerpeksag** [comment]
It's because `result` is set to `0` here: https://github.com/python/cpython/blob/985f0ab3ad5e8e9a8d7fc53026c38390b1f2b466/Python/bltinmodule.c#L2296

Then Python basically tries to do:

```py
result = 0
for item in ('a', 'b', 'c'):
    result += item
```

You can create a bug report at bugs.python.org and ask if it's possible to improve error message, but I'd expect it's going to be rejected since it's a rare usage.
