### ISSUE TITLE
32 or 64 bit?

### ISSUE THREAD

**Issue by cvhorie** [python/pythondotorg#1651]
I have Win 10 64 bit Dell.  My previous installations of Python have been 64 bit, but the download I was offered just now was 32 bit. I had to search to find the 64 bit option. Does the Download page assess the computer system before offering an option? 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
No dear.. If you are downloading Python from the original website i.e. https://python.org/ ,  the website does not provide you the files with respect to your system, it just provide you all releases and you can download the one you want.. But by the way if you still having this error then you will give the information about your os, processors, and the version you want to download so that I can provide you the direct link to download python...

Thanks
Regards

**Comment by ghost** [comment]
Note: You can run 32 bit file on a 64 bit os but not vice versa..

**Comment by ghost** [comment]
But if you want to download latest version of python ; The links are:

1) For windows 64 bit 
https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe

2) for windows 32 bit : https://www.python.org/ftp/python/3.9.0/python-3.9.0.exe


;) Thanks

**Comment by ned-deily** [comment]
For Python 3.9.0 and newer releases, the Windows download button defaults to downloading a 64-bit version.  Previous versions, including new releases of 3.8.x, continue to default to 32-bit versions.  You can find all the available downloads for Windows by clicking on "Windows"  in the text box towards the top of the main downloads page (https://www.python.org/downloads/) or the Windows option on the left of the Downloads pop-up window.  Both take you to https://www.python.org/downloads/windows/,
