### ISSUE TITLE
[Urgent]Cannot generate xml test report with msg "AttributeError: '_SubTest' object has no attribute 'elapsed_time'".

### ISSUE THREAD

**Issue by winnie-py** [python/pythondotorg#1660]
**Describe the bug**
Cannot generate xml report with below msg:
Traceback (most recent call last):
  File "test_all.py", line 14, in <module>
    xmlrunner.XMLTestRunner(output=report_dir).run(createsuite())
  File "C:\Python37\lib\site-packages\xmlrunner\xmlrunner.py", line 421, in run
    result.printErrors()
  File "C:\Python37\lib\unittest\runner.py", line 110, in printErrors
    self.printErrorList('FAIL', self.failures)
  File "C:\Python37\lib\site-packages\xmlrunner\xmlrunner.py", line 217, in printErrorList
    '%s [%.3fs]: %s' % (flavour, test_info.elapsed_time,
AttributeError: '_SubTest' object has no attribute 'elapsed_time'

**To Reproduce**
1. Use self.subtest method of unittest to run the tests in cycle.
2. Use xmlrunner to run the tests then generate xml test report.

**Expected behavior**
"Generating XML reports..." should work well.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 64bit
 - Version: Python3.7.4 xmlrunner 1.7.7(latest version)

**Additional context**
1. Enconter this issue on 29th Sep, 2020 (UTC+8) suddently, it works well before that day on the same PC.
2. It only fails on one PC, but works on others.
3. Have tried to uninstall/install python/packages, restart the PC, but still failed.

**Comment by berinhard** [comment]
Hi @winnie-py, thanks for opening this issue but it's not clear for me how to properly reproduce the error.

I couldn't find a `test_all.py` script in the repository. I used [Gtihub's find tool](https://github.com/python/pythondotorg/find/master) to do so. Also, I couldn't find the `xmlrunner` as a project's dependency since it's not listed in [`base-requeirements.txt`](https://github.com/python/pythondotorg/blob/master/base-requirements.txt) and neither in [`prod-requeirements.txt`](https://github.com/python/pythondotorg/blob/master/prod-requirements.txt) or [`dev-requirements`](https://github.com/python/pythondotorg/blob/master/dev-requirements.txt).

Anyway, one thing I've noticed is that you're using Python 3.7 when the [installing docs](https://pythondotorg.readthedocs.io/install.html#manual-setup) instructs to use 3.6 instead. I don't know if this is related with the error, but maybe it's something to consider.

Can you provide more information about it?

**Comment by hugovk** [comment]
@winnie-py This is the repo for the https://python.org **website**. It sounds like you should report this elsewhere, maybe at https://stackoverflow.com/ or https://github.com/xmlrunner/unittest-xml-reporting/issues, and https://github.com/xmlrunner/unittest-xml-reporting/issues/218 might help.

**Comment by ewdurbin** [comment]
Agree with @hugovk, this does not appear to be an issue with pythondotorg codebase.
