### ISSUE TITLE
Procedure For Contributing To pythondotorg

### ISSUE THREAD

**Issue by alvindera97** [python/pythondotorg#1736]
Good day engineers,

Thank you for all the great work you put into python's website, however I do have a nagging question: **Is there a particular procedure for contributing to pythondotorg's repository**? The reason why I am asking this question is that I had submitted 2 PRs since last year and it doesn't seem like it has been checked or commented on. I would really love to contribute to this website because I love python and I love django. 

If I am just intruding with my code or my changes [especially with my current approach], I would really love it if I am directed through the right medium to submit/suggest changes. 

Thank you for your time and I hope a favourable reply.

**Comment by berinhard** [comment]
Hi @alvindera97, hope everything is fine with you!

First of all, thanks for the interest and time to contribute to python.org! It's very importantant for the project and the Python community to have new people helping it to grow.

I received and read your email but I fell I'm not the best person to help you with your questions. I'm also a new contributor, but I'm helping PSF with very specific changes into python.org for now. That's why, although I saw your PR, I didn't feel comfortable approving/rejecting it. This, plus the upcoming 2021 PyCon, is asking for a lot of focus and priority from several contributors for now and for sure that this impacts on PRs being open with no reviews for longer than it would be ideal. 

About your approach, a friendly feedback and **personal opnion** is to not reach project's developers via their personal emails asking for revierws. I maintain myself two open source projects ([pyp5js](https://berinhard.github.io/pyp5js/) and [model-bakery](https://github.com/model-bakers/model_bakery)) and I can tell you that this kind of direct communication leads me to anxiety and stress. But, feel free to keep on posting and asking for reviews here, in Github.

All the best for you!
