### ISSUE TITLE
some problems in pep8 web view

### ISSUE THREAD

**Issue by 1-0** [python/pythondotorg#1772]
I try to use reference https://www.python.org/dev/peps/pep-0008/#id49
(to "Designing for Inheritance" on pep8 page)

But in my browsers (firefox, opera, - in win10 chromium - in xubuntu 20.04) was opened only
https://www.python.org/dev/peps/pep-0008/#id14 (to "Introduction")

**Comment by 1-0** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/762649/119146079-f24ab900-ba52-11eb-8b22-dd21f69761e8.png)
![Screenshot_2](https://user-images.githubusercontent.com/762649/119146081-f2e34f80-ba52-11eb-8755-b66aecc1ae02.png)

**Comment by ned-deily** [comment]
Thanks for the report. I'm not sure if I totally understand the problem (and things may have changed since you opened the issue) but I think the problem here is that you trying to use the auto-generated `#idxx` tags as permalinks. Those numbers can change as PEPs are modified. Currently, if you look at the link to the `Designing for Inheritance` section in the contents section at the top of the PEP, the link there is https://www.python.org/dev/peps/pep-0008/#designing-for-inheritance. That link should remain permanent, assuming that section of the PEP is not altered or removed.
