### ISSUE TITLE
Remove "This version of Python can't be used on Windows 7 or later"

### ISSUE THREAD

**Issue by devashish2024** [python/pythondotorg#1832]
Remove "This version of Python can't be used on Windows 7 or later" From website and talk as the Windows 7 Service Pack 1 Or Higher can be used for Python.

**Comment by mborus** [comment]
Did you manage to install the latest Python 3.9.6 on Windows using the installer?

If you did, then that's a bug because the installer should stop you from installing it.

The reason: It's no longer supported and if you somehow manage to get it to run, 
(which you probably can for large parts of the code) all problems you encounter are 
your own and should not get reported as bugs.

**Comment by devashish2024** [comment]
yeah but win-7 sp1 supports some

**Comment by ned-deily** [comment]
@zooba, comments?

**Comment by devashish2024** [comment]
I am meaning, that in some versions of windows, there have some editions of Python installable, even before on Windows 7. Windows 7 Service Pack 1 is good than the default windows 7. Windows 7 service pack 1 can run some editions of python, but not all. Its what I mean.

**Comment by zooba** [comment]
Where's the text we are discussing?

Some older versions of Python will still _run_ on Windows 7, and IIRC there were some security fixes in SP1 that we do require. There certainly shouldn't be any current references to Win7 though.

**Comment by devashish2024** [comment]
Ok. If I am right, do it else just end the talk. Closing as you wish.
