### ISSUE TITLE
license command in python 2.7.5 returns 404 url

### ISSUE THREAD

**Issue by hannseman** [python/pythondotorg#197]
```
$ python
Python 2.7.5 (default, Sep 25 2013, 12:05:55)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.75)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> license
See http://www.python.org/2.7/license.html
```

[http://www.python.org/2.7/license.html](http://www.python.org/2.7/license.html) returns a 404.

**Comment by ned-deily** [comment]
Thanks for the report.  The above link now redirects to the license page.  Note that the above message with the URL is only displayed if the license file cannot be found locally; normally it is included as part of a Python installation.  Also, I've opened an issue (http://bugs.python.org/issue21572) to change future releases to fall back to a release-independent license URL so that this problem won't occur in the future.
