### ISSUE TITLE
Broken link on Success Stories page

### ISSUE THREAD

**Issue by dorfire** [python/pythondotorg#227]
http://python.org/success-stories/
"Tell us your story" link at the bottom of the page.

**Comment by malemburg** [comment]
This is on purpose, since the processes for using the success story system on the new site have not yet been hashed out.

At the moment, it's best to submit success stories by sending an email to the PSF Python Brochure team at brochure@getpython.info. This newsletter gives some guideline on how to write success stories: http://brochure.getpython.info/news/newsletter-1-we-need-your-help

We should probably create a separate page on the site for this.

**Comment by frankwiles** [comment]
Fixed long ago, but not closed.
