### ISSUE TITLE
"Other" as category or type?

### ISSUE THREAD

**Issue by smontanaro** [python/pythondotorg#245]
Should both the category and job types sections have "Other" as a choice?

**Comment by SarahPythonista** [comment]
Category currently has "Misc" as an option. It is listed in alphabetical order between "Manager" and "Operations Engineer".

I think this is non-intuitive. I'd probably call it "Other" (as you suggested), but whatever it's called, it should be the last option listed (easier to find this way). 

If you didn't see it, other people will also miss it. 

I don't see a "Job Types" menu. Do you mean Job Technologies? (I see a free form field there that might not have existed when this issue was opened).

**Comment by frankwiles** [comment]
I could be wrong but I read this as 'Other' with option to enter random text.

**Comment by malemburg** [comment]
We now have "Other" as category and the other option field for job technologies (job types).
