### ISSUE TITLE
Body of /community is nearly empty below the fancy looking boxes

### ISSUE THREAD

**Issue by sdeibel** [python/pythondotorg#337]
The page at /community contains just a header "Community List" and no content.  I would like to recommend placing the "How to Contribute" list from /about/help here and also another section w/ info on how to contribute to the website (link to github, etc).

**Comment by berkerpeksag** [comment]
The "Community List" section is not displayed since b1f072bdcaacc74d526a4cc9043bafbfd3475706. There is already a "Contributing" menu in every python.org page so I'm not sure if we should duplicate that information.

Also, the community application is not completed. It only show items from the `Post` model. Templates for `Link`, `Photo`, `Video` models aren't implemented. To be honest, I don't what is the use case of the community application.

@MarkMangoba @ejodlowska do you remember why we need the "Community List" feature? Is there any mockups that I can use or can we remove these unused features?

**Comment by sdeibel** [comment]
I'm fairly sure back when I made this issue that the Contributing menu area was not there and the site menus in general were different.  Thus I'm closing this issue.
