### ISSUE TITLE
PSF: no email confirmation sent when new member signs up

### ISSUE THREAD

**Issue by tbm** [python/pythondotorg#395]
I went to https://www.python.org/users/membership/ and entered my details.  I never received a confirmation email that I'm now a PSF member.

Note: I see that this page requires you to be logged in now.  This wasn't the case yesterday.  I visited the page when I was not logged in, entered my details (name, email, city, zip code, etc) and got a confirmation page -- but no confirmation email.

**Comment by rasselin** [comment]
I'm also having this issue, but for this link: https://pypi.python.org/pypi?%3Aaction=register_form
Registering with launchpad openId didn't work either.

**Comment by merwok** [comment]
PyPI is wholly separate from pydotorg; bugs in the codebase use a Bitbucket issue tracker, and support requests use an old Sourceforge tracker (yeah, this is confusing, and I don’t know which one your issue is; I would use the Bitbucket tracker as it may have more people watching it).

The links to these trackers are found on the left sidebar of any PyPI page.

**Comment by jutrasm** [comment]
I had similar confusion.  Upon seeing a tweet that there were new membership options, it made me wonder if I was already a member.  I already had a python.org login set up, but went to the new member signup - as a result of that I was prompted to go to my email and confirm and that was it.  I'm still not sure if I'm considered a "member".  Furthermore, I would like to be considered a "contributing member" since I've been volunteering for the Jobs Board for the past few months.  I don't know how to designate that class of membership. I opened a new issue #398 regarding designation of class of membership.

**Comment by MarkMangoba** [comment]
Consolidating psf-membership tickets with the new integration with CiviCRM.

**Comment by MarkMangoba** [comment]
Consolidating psf-membership tickets with the new integration with CiviCRM.
