### ISSUE TITLE
legacy.python.org ... Official Website

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#430]
https://www.python.org/  search for pep-8
click click click...  get to: https://www.python.org/doc/essays/styleguide
click on pep-8: http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length

I am not sure if legacy.python.org is expected. 

If it is, then I think this should be fixed:
http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length
upper corner, python logo links to http://legacy.python.org/  

which says "Python Programming Language – Official Website"

**Comment by ned-deily** [comment]
So far, the peps have not been ported over to the new website; I"m not sure who is working on that.  In the meantime, the legacy website has been updated so that the homepage logo now links to the new website; thanks for the suggestion.  Also, the legacy site homepage now includes a note that the legacy site is not being updated and refers to the new website.
