### ISSUE TITLE
Add redirect for old PEP 263 link

### ISSUE THREAD

**Issue by mjpieters** [python/pythondotorg#466]
Python 2.3 through to 2.7 will link to http://www.python.org/peps/pep-0263.html when bytes outside the ASCII range are found when tokenizing a source file.

Unfortunately, that specific URL ends up redirecting to http://legacy.python.org/dev/peps/, a not-so-helpful location, one step short of actually linking to the specific PEP.

Can a new redirect be added to Python.org to ensure that anyone running into this error using Python 2 still can find the correct documentation?

Python 3.x and any future 2.7 releases (see [this recent commit](http://hg.python.org/cpython/rev/f80199b009ef)) are not affected.

**Comment by ned-deily** [comment]
It turns out there already is a redirect defined for that url but it's not working.  My guess is that the incomplete PEP application and url definitions for it are getting in the way.  The migration of peps from the legacy site to the new one is being planned right now as part of phase 2. (See also #297.)  Fixing this redirect should be included.

**Comment by juliantaylor** [comment]
redirects should also be added for pep 7 and 8 those are referenced in a lot of third party documentation
