### ISSUE TITLE
Python 2.5 documentation links are broken

### ISSUE THREAD

**Issue by dir-ableton** [python/pythondotorg#474]
See e.g.

 https://www.python.org/doc/2.5/whatsnew/whatsnew25.html
 https://www.python.org/doc/2.5/ext/ext.html

**Comment by ned-deily** [comment]
Thanks for the report.   I assume you found those links on either https://www.python.org/doc/2.5/ or https://www.python.org/doc/2.5/download/.  For that release, as well as for the 2.4.4, 2.5.2, and 2.5.4 releases, there were doc/x.x and doc/x.x/download pages on the legacy web site that depended on some redirects and those were not transitioned to the new site.  Rather than continuing those special cases, I've edited the two pages for each of those releases on the new web site so they now have valid links, for example:

https://docs.python.org/release/2.5.4/whatsnew/whatsnew25.html
https://docs.python.org/release/2.5.4/ext/ext.html

If you know of other pages where the original links appear, let us know.

https://www.python.org/doc/2.4.4/
https://www.python.org/doc/2.5/
https://www.python.org/doc/2.5.2/
https://www.python.org/doc/2.5.4/
