### ISSUE TITLE
Move sign in dialog to the community page

### ISSUE THREAD

**Issue by pitrou** [python/pythondotorg#536]
As has been pointed out, "signing in" is completely unimportant when you want to download Python, browse the docs, or even contribute or participate in the community. It should be moved out of the top page and in a dedicated box in the community page, with a text explaining that it's totally optional even for contributing.

**Comment by lac22** [comment]
Why hasn't this been moved yet?

**Comment by frankwiles** [comment]
@lac22 PSF needs to make a decision on it

**Comment by lac22** [comment]
Date:    Fri, 20 Feb 2015 10:49:06 +0100
To:      psf@python.org
cc:      lac@openend.se
From:    Laura Creighton lac@openend.se
Subject: PSF basic membership launched

Okay, now that this has been launched we need to get the 'login' stuff
off the front page, and every other page of the python.org site and
back to part of the PSF pages only.  Right now I don't even know if
the front page register is a PSF member register -- it doesn't say
so. It seems to link to the same place https://www.python.org/accounts/login/

Since we don't want everybody on the planet thinking they have
to become PSF members python community, to use python, or to use
the documentation, we need to get this off the front page.  Especially
since being a PSF member has some implications about agreeing to
the Code of Conduct, while https://www.python.org/accounts/login/
just signs people up willy-nilly whether or not they agree, or even
know about the CoC

The register page needs some more changes, aside from clearly identifying
it as something that is about the PSF. Somebody, not webmaster,
who thinks that having lots of basic PSF members is a great idea
needs to volunteer to greet these people, talk to them about whatever
it is that needs talking about, thank them for joining, and, very most
importantly _have a link set up so they can get the mail when these people
run into trouble with the registration process, do not get their confirmation
email, decide they want to change their account name, etc.
I suspect this should be a mailman mailing list, but I will leave the
implementation details to those who care about such things.

The important thing is that webmaster needs to know where to forward
all the 'I have a basic PSF membership problem emails', for the people who
don't read the improved https://www.python.org/accounts/login/

This mail also added to https://github.com/python/pythondotorg/issues/536

Laura

**Comment by lac22** [comment]
ooops, didn't mean to close this, it close and comment by mistake.

**Comment by malemburg** [comment]
I disagree with removing the login details from the pages.

The login is not only needed for PSF membership signups, but will later on also be used for e.g. customizing the user experience, getting editing access to parts of the website and getting read access to pages which are only available to a subset of the visitors. The PSF membership signup is a different process, which you have to run through after getting a python.org account.

It's better to explain somewhere (e.g. on https://www.python.org/accounts/signup/) what getting an account on python.org means and why it's useful to have. The page currently just has a warning that signups are not needed to download Python, which while true, doesn't look very inviting.

BTW: The big picture plan is indeed to get as many Python community members signed up to the PSF as possible. We want the PSF to become a big family :-)

**Comment by pitrou** [comment]
> will later on also be used for e.g. customizing the user experience, getting editing access to parts of the website and getting read access to pages which are only available to a subset of the visitors

Then let's talk about it again when that part is actually ready.

**Comment by malemburg** [comment]
@pitrou This is being worked on. I don't see a need to remove the login feature now, only to add it back again in a few months. I frankly don't understand where you are getting the idea from that people will think they have to sign up to anything to download Python :-)

**Comment by pitrou** [comment]
>  I don't see a need to remove the login feature now

I really don't care if you don't understand. Please don't clobber the Python front page with useless crap. This is not your personal toy.

**Comment by pitrou** [comment]
One more thing: don't be surprised that people react violently when faced with the done deal when everything is done behind closed doors.

**Comment by lac22** [comment]
In a message of Fri, 20 Feb 2015 02:16:25 -0800, Marc-Andre Lemburg writes:

> I disagree with removing the login details from the pages.
> 
> The login is not only needed for PSF membership signups, but will later on also be used for e.g. customizing the user experience, getting editing access to parts of the website and getting read access to pages which are only available to a subset of the visitors. The PSF membership signup is a different process, which you have to run through after getting a python.org account.

And I am utterly hostile to this entire idea.  I don't want any part of
python.org to be only available to a subset of the visitors.  If you
want private stuff like that, put it someplace else.  You cannot have
an open community where some things aren't open.

> It's better to explain somewhere (e.g. on https://www.python.org/accounts/signup/) what getting an account on python.org means and why it's useful to have. The page currently just has a warning that signups are not needed to download Py
> thon, which while true, doesn't look very inviting.

I don't know of any advantages of having a python.org account.  The only
thing that I think there is an advantage in having, is an account to
edit the wiki, and _this account doesn't let you do this_.  You have to
get a separate account to use the bugtracker, and to upload to PyPI.
Now, if there were any plans to integrate that into a python.org account,
I might be positive about the idea.

But this follows the rule that you need an account to upload content.
For people who don't want to do this, there ought to be no advantage
in having an account.  And if there is something like this planned,
I will be first in the queue of people wanting to stamp this out.
Python is for everybody, not a self-selected clique.

> BTW: The big picture plan is indeed to get as many Python community members signed up to the PSF as possible. We want the PSF to become a big family :-)

Right, then somebody who sees the value in having the PSF become a
big family has to take over the duties of managing the big family, so it
doesn't have to be done by the volunteers who are webmaster.  It is not
fair to load us down with all the 'I never got my confirmation
email' problems.

And if an account on python.org is to be something separate from a
basic PSF membership then that needs to  be outlined very clearly.

That I have to make comments like this is an indication that this thing
_was in no way ready to go live_.  And you launched it anyway.  Either
fix it immediately, or unlaunch it, take it back to the workshop and
launch it later when it is ready.  And next time, before you launch
such a thing, _tell webmaster about it before it goes live as a bit
of basic courtesy_.  We don't want the first time we hear about a
new thing called a PSF basic membership going live to be the complaints
from people who didn't get their confirmation email.  We need to know
what we are supposed to say to these people, and we need to have it
handy.

There is an automatic response we hand to people who send mail to
webmaster, and all of this sort of stuff badly needs to go in there,
so we don't have to send answers out by hand -- but since we have
no clue whom we should send these people to, and what should be done
about it we don't know what to put in the automatic response mail,
either.

Laura

**Comment by malemburg** [comment]
On 20.02.2015 11:35, Antoine Pitrou wrote:

> ```
> I don't see a need to remove the login feature now
> ```
> 
> I really don't care if you don't understand. Please don't clobber the Python front page with useless
> crap. This is not your personal toy.

Oops. Are you having a bad day ? :-)

## 

Marc-Andre Lemburg

**Comment by pitrou** [comment]
> Oops. Are you having a bad day ? :-)

No, we're just having a clueless PSF board. That's no news though.

**Comment by malemburg** [comment]
@lac22 I understand you being upset about support emails going to the webmaster address and that we should do something to address this, but don't think that removing the login buttons is the right answer to this.

Regarding your other points:

Private sections of the website: Things like e.g. the job board postings may only be edited by the users who have entered them or the job board reviewers. User groups and other project groups may well want to use the site to maintain their internal documents, so we need to be prepared for this as well. This is not about open vs. closed, it's about having people use the site or not.

There's no Spanish Inquisition here :-)

An example of where an account is useful (apart from the above): Having  a python.org account will allow you to e.g. set your time zone so that event calendars can present times in your local time zone rather than UTC. I can also imagine getting notifications for certain interesting topics, or signing up for newsletters.

**Comment by holdenweb** [comment]
> Oops. Are you having a bad day ? :-)

I really don't think that sort of condescension belongs in the bug tracker, or anywhere else.

It's obvious that the whole web development effort is being inadequately managed by an over-extended board, but whatever the answer IS, it is not to defensively diss those who are still, despite being completely excluded from any part of the decision-making process, trying to move things forward.

If Laura WAS having a bad day it was brought on by ill-thought-out developments that caused her extra(volunteer) work. I'm getting a little snippy about it myself.

**Comment by malemburg** [comment]
On 20.02.2015 13:00, Steve Holden wrote:

> I really don't think that sort of condescension belongs in the bug tracker, or anywhere else.

Steve: You may want to check the context of the quote.

It's fine that Antoine disagrees with my opinion. It's not fine
that he raises a personal attack and later extends this to the
PSF board as a whole.

FWIW: I was not involved in the redesign project at all.

## 

Marc-Andre Lemburg

**Comment by holdenweb** [comment]
I'm sorry, I misread that as a snide comment about Laura's contribution to the issue.

Anyway, no disrespect to anyone who'd trying to get things done whether they were originally part of the project or not.

S

On Feb 20, 2015, at 7:24 AM, Marc-Andre Lemburg notifications@github.com wrote:

> > I really don't think that sort of condescension belongs in the bug tracker, or anywhere else.
> 
> Steve: You may want to check the context of the quote.

## 

Steve Holden steve@holdenweb.com +1 571 484 6266 @holdenweb

**Comment by lac22** [comment]
In a message of Fri, 20 Feb 2015 02:22:20 -0800, Marc-Andre Lemburg writes:

> @pitrou This is being worked on. I don't see a need to remove the login feature now, only to add it back again in a few months. I frankly don't understand where you are getting the idea from that people will think they have to sign up to anything to download Python :-)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/python/pythondotorg/issues/536#issuecomment-75216793

People already have this idea.  They write to webmaster about it.

Laura

**Comment by lac22** [comment]
Right now due to DMARC damage control, mail.python.org is munging the mail addresses of people from jpmorgan.com, unknown.com, yahoo.com or aol.com.   Any email that is sent to any @python.org address gets.dmarc.invalid appended to the domain of the From: address by Postfix at
incoming smtp time.  See https://mail.python.org/mailman/private/infrastructure/2015-April/002926.html

This means that nobody from these domains can register, and so they complain about not getting
their valdation email to webmaster(me) which wastes my time.

**Comment by holdenweb** [comment]
The fact that signup isn't required won't stop people signing up. Which means we at webmaster@ get the mails. Please, can't we just remove the login-related features from the templates? We almost certainly don't need to disable any code to do that, so "reinstallation" should be relatively simple. Or am I missing something? These emails are a pain, and totally unnecessary. We see quite enough volume on webmaster@ without vacuous support requests.

On Feb 20, 2015, at 1:37 PM, lac22 notifications@github.com wrote:

> In a message of Fri, 20 Feb 2015 02:22:20 -0800, Marc-Andre Lemburg writes:
> 
> > @pitrou This is being worked on. I don't see a need to remove the login feature now, only to add it back again in a few months. I frankly don't understand where you are getting the idea from that people will think they have to sign up to anything to download Python :-)

## 

Steve Holden steve@holdenweb.com / +1 571 484 6266 / +44 113 320 2335 / @holdenweb

**Comment by berkerpeksag** [comment]
I don't have any strong opinion on this, but to make this forward here is a simple CSS patch: https://github.com/python/pythondotorg/pull/730

**Comment by berkerpeksag** [comment]
Can we now revisit this issue and try to reach a consensus? I've opened #730 to resolve this issue and I'd like to merge or close it to reduce our PR backlog.

(Pinging @MarkMangoba and @ejodlowska since this issue is labeled as "psf-review".)

**Comment by MarkMangoba** [comment]
being closed by #730
