### ISSUE TITLE
"BETA" should be removed from the logo

### ISSUE THREAD

**Issue by 1st1** [python/pythondotorg#64]
"BETA" in the Python logo may confuse new users (or corporate people, which is even worse) that it is Python, The Language is in BETA, not the website.

**Comment by riccardo-forina** [comment]
Agree, I have had the same feeling. :+1:

**Comment by yaph** [comment]
Came here to add the same issue, apparently many other people think so too. See [this discussion](http://www.reddit.com/r/Python/comments/1ydxil/the_redesigned_pythonorg/) on Reddit and the [top and follow-up comments](http://www.reddit.com/r/Python/comments/1ydxil/the_redesigned_pythonorg/cfjsb1f).

**Comment by ghost** [comment]
I'm pretty sure anyone who is going to use Python knows it isn't in beta. Corporate people can be shown the release history on 2 and 3 to see it isn't in beta. The site itself is in beta meaning not everyone will see it right now when they go to python.org. Some people need to go to http://preview.python.org/ in order to see the site.

**Comment by yaph** [comment]
@cameff it's not about the people who know Python, those who don't might just leave immediately, because of that 1st impression.

**Comment by 1st1** [comment]
> The site itself is in beta meaning not everyone

There are other methods of explaining that site is in beta, besides modifying official Python logo.

**Comment by peterlandry** [comment]
If it causes this much discussion, I think it should go. But, it's really not, imo, a problem either way.

**Comment by ghost** [comment]
@yaph I find it hard to believe that someone new to programming would go to the site and then not use the language because the logo says beta. People just don't stumble onto Python, it's recommended to them or they hear about it from having other development experience. Also someone new to programming would not be thinking about things being in beta and whether or not you should use it in production or not. The vast amount of learning resources that are going to expose newcomers to python I think demonstrate that it's a solid language that has been around for some time. I'm sure they will remove the beta when everyone has access to it.

**Comment by riccardo-forina** [comment]
Unfortunately the chain of command isn't always composed by developers. A manager can associate the beta label to the product itself just because he knows nothing about Python, and also he _doesn't care_.

Anyhow, this can be solved just by moving the label to the classic ribbon in an angle of the website -  maybe changing the label to something like "website in beta" - and be done with it.

**Comment by yaph** [comment]
:+1:  @riccardo-forina

**Comment by 1st1** [comment]
@cameff I really don't get your arguments. What's the point of having this BETA label at all? It confuses people? Yes, it confuses me, other people in this thread, people on hacker news and reddit. Isn't it enough for you?

And the site is not beta now too. It's live. Yes, it has bugs, but those bugs we'll be addressed soon. Please stop advocating for keeping this label.

**Comment by ghost** [comment]
@1st1 It's not live for everyone, if I visit from my home computer the old site is displayed and I have go to python.preview, but at work I can view it. I really don't see how this is confusing, but whatever.

**Comment by takluyver** [comment]
Even if it's made clearer that it means the site, not the software, I'm not sure the 'beta' logo is useful. For software, beta means "you might want to stick with the last version while we make this a bit more solid". But there's no obvious way to get the old site, so it doesn't make any difference to visitors that the new site is in beta.

**Comment by fcurella** [comment]
ref #140

**Comment by alex** [comment]
This is fixed.
