### ISSUE TITLE
Remove the feedback bar from the footer.

### ISSUE THREAD

**Issue by 1st1** [python/pythondotorg#65]

**Comment by gvanrossum** [comment]
Why remove it? Don't you want feedback? Or maybe replace it with a link to the github tracker?

**Comment by 1st1** [comment]
A link to this github repo would be great, and probably enough. I myself needed to post on one of python mailing lists to get an idea of where to put my feedback.

The feedback bar also has a lot of references to the beta period (checkbox to make you a "beta tester" etc).

**Comment by 1st1** [comment]
There is also a vertical feedback button, glued to the right side of the page. We can retarget that one to point to this repo's issues.

**Comment by birkenfeld** [comment]
If the feedback submitted there is acted upon (where does it go?), it is still much easier for casual visitors to report issues there than here.

After a while, when "trivial" problems like missing content or broken links are sorted, I would leave only a link to this tracker.

**Comment by benjaminp** [comment]
I agree. The feedback table is full of spam, and I doubt anyone is ever going to read through it. Issues should now be submitted here on GH.

**Comment by malemburg** [comment]
I opened #189 to address the github tracker link request.

**Comment by birkenfeld** [comment]
OK, the feedback goes into a table in the DB. There's no spam protection, so we have over 16'200 feedback entries, mostly advertising medical supplies and worse.

Looking at that I recommend disabling the form ASAP to avoid frustrating users with genuine feedback by ignoring them.

**Comment by malemburg** [comment]
Agreed. Related to this, I've opened #190 to address the obvious spam signup issue we will need to solve somehow.

**Comment by malemburg** [comment]
Can we get an export of the feedback table to try to filter out the ham entries ?

**Comment by benjaminp** [comment]
Here's is a an export of the table in [pg text format](http://www.postgresql.org/docs/current/static/sql-copy.html#AEN69009) with names and emails removed: http://python.org/~peterson/feedbacks.tar.xz

**Comment by malemburg** [comment]
On 25.02.2014 16:14, Benjamin Peterson wrote:

> Here's is a an export of the table in [pg text format](http://www.postgresql.org/docs/current/static/sql-copy.html#AEN69009) with names and emails removed: http://python.org/~peterson/feedbacks.tar.xz

Thanks, Benjamin. In order to put the data through an email
junk filter tool it would be useful to have both names and emails
as well, esp. since the table does include some easily recognizable
names from the community.

Could you perhaps send the dump by email with those fields
included ?

## Thanks

Marc-Andre Lemburg

**Comment by johanovic** [comment]
I agree with @malemburg  that the names might be helpful, but I think that would be a privacy infringement. I don't think actual people inputting their name want some bot to start spamming them.

A few things we could already do, we could rank the comments on spamminess with a little algorithm that takes into account
1. Whether there is a link. Most spam has links, but useful feedback mostly has little to few _external_ links.
2. We could run NLTK and extract the keywords of this document. Then we could select about 200 words (sex, hot, lolita, porn, girl, etc.) that will mark a post as spam.
3. Anything that is not in English
4. (with a little less weight) we could data mine the python website and give more value to any post that contains keywords on the python website (python, programming, code, etc.)

I think this is worthwhile because a) we want feedback as @gvanrossum said and b) we can't expect 'regular' website users to post a github issue and c) **there are valuable comments in the feedback**, a few examples:

6547    \N  \N  This page has broken images.    2014-02-20 06:12:37.638557+00
7182    \N  \N  Latest news (9/29/2012Python 3.3.0 released)! It's 2014 already     2014-02-20 14:59:40.188696+00
7183    \N  \N  It'd be nice if Python has a presence in federated social networking sites such as pump.io[1], GNU Social[2]. \r\n\r\nIn case you sign up for any of them, do them under "Socalize" . \r\n\r\nThanks for paying heed!\r\n\r\n[1]:  http://pump.io\r\n[2]:  http://gnu.io    2014-02-20 15:00:22.607498+00
5915    \N  \N  This page does not work. I want to read the Python Style Guide. There's HTML markup where there should be text.\r\n\r\nThe link in the footer to PEP Index returns a 404.   2014-02-19 23:01:01.39653+00
7208    \N  \N  The favicon for the new site needs work. An artist needs to take the Python logo, reduce it to favicon size (16 pixels square? other sizes too?) and tweak the pixels individually. The current favicon is pretty bad. For one thing, it changes the shape of the logo, a TM no-no. 2014-02-20 15:20:34.372968+00

Essentially **we need to make sure the form does not accept links** and we will already trim down a lot of the spam. I will create an issue for this.

Just a few ideas here.

**Comment by fcurella** [comment]
@wcapio: feedback pk# 7183 in the sample data you posted is ham but has a link that would be filter out by your proposal. Maybe we can try a less aggressive approach first (as in #208) and see how that plays out?

**Comment by malemburg** [comment]
On 26.02.2014 13:51, Flavio Curella wrote:

> @wcapio: feedback pk# 7183 in the sample data you posted is ham but has a link that would be filter out by your proposal. Maybe we can try a less aggressive approach first (as in #208) and see how that plays out?

I think we should simply direct users to the github tracker instead of
reenabling the feedback logic. There's no easy to use interface to
read the feedback that goes into the table, so the feedback stored there
will likely not be used much.

I will try to filter the current table contents a bit and then see
whether it's useful to upload it to the github tracker.

## 

Marc-Andre Lemburg

**Comment by johanovic** [comment]
I don't think the solution to "we are getting spam" is "we don't want feedback". I can see your point on using github and on the fact that the feedback might not be used if not in github. 

I think we can
- not accept external links. This will cause an error message on the bots filling out the form that they will not know how to handle. @fcurella the example of pump.io, for instance, does not need the link, the name is enough.
- a honeypot, cf. https://github.com/python/pythondotorg/pull/208
- a captcha
- some more advanced spam system... surely some python developper has already developed this.

I agree with @malemburg that the managers of the website will need to go through the admin interface to read the comments... Maybe that will break the workflow too much. Or maybe someone could simply do that task regularly.

**Comment by benjaminp** [comment]
I think we should send everyone here, perhaps with a link on every page. Plenty of people have found this tracker even without a link. It's also much easier to discuss and act on feedback with a real issue tracker than a database table.

**Comment by birkenfeld** [comment]
I agree with Benjamin.

**Comment by 1st1** [comment]
There was a small yellow vertical button "feedback" with an icon. Can we return it back on the site, and make it point to this issues page?
