### ISSUE TITLE
Python 3.4.3 install didn't work

### ISSUE THREAD

**Issue by GilDawson** [python/pythondotorg#734]
Following the Amazon AWS documentation (>>), I wished to upgrade my current version of Python (included with MacOS 10.6.8)

$ python --version
Python 2.6.1

AWS said 

> > If you don't have Python installed, install version 2.7 or 3.4 using one of the following methods:
> > On Windows or OS X, download the Python package for your operating system from python.org and run the installer. These installers include pip.

I downloaded "python-3.4.3-macosx10.6.pkg" (took about 3 minutes) and launched it.  The installation appeared to stall during "Running Package Scripts", but eventually completed successfully.  

When it was done, I tested for success...

$ python --version
Python 2.6.1

...and was disappointed to learn that python had not been upgraded.  
Also, despite the fact that the AWS documentation said

> > These installers include pip.
> > My test...

$ pip --help
-bash: pip: command not found

...suggests that this one did not.

I repeated the whole download/install process and got the same results again.
What, do you suppose, I did wrong?

--Gil

**Comment by ned-deily** [comment]
Gil, this issue tracker is for issues with the python.org website, not with Python usage questions.  Good places to ask such questions are the Python list (https://mail.python.org/mailman/listinfo/python-list) or one of the StackOverflow sites (http://stackoverflow.com).  That said, you probably didn't do anything wrong.  Python 3 is installed as `python3` so that it can co-exist with Python 2 installations (`python`).

**Comment by GilDawson** [comment]
Well, that worked!

$ python3 --help
usage: /Library/Frameworks/Python.framework/Versions/3.2/Resources/Python.app/Contents/MacOS/Python [option] ...

Thanks, ned!

My apology, but I had thought the problem might have been with the website itself (wrong file or something.)

--Gil
