### ISSUE TITLE
It’s Mac OS X, not Mac OSX

### ISSUE THREAD

**Issue by hynek** [python/pythondotorg#75]
…in the Downloads pop-up menu. :)

(and on http://www.python.org/downloads/mac-osx/)

Technically it’s just “OS X” nowadays.  Apple has dropped the “Mac” part some time ago.

**Comment by fcurella** [comment]
Pretty sure 'Mac OSX' is wrong, but I don't know which is more correct between 'Mac OS X' and 'OS X'. Is there any 'official' document from Apple about this?

**Comment by hynek** [comment]
I’m not sure whether there has been an official announcement (and have no time to search for that) but Apple itself refers to it exclusively as “OS X”:
- http://www.apple.com/osx/
- http://images.apple.com/media/us/osx/2013/docs/OSX_Mavericks_Core_Technology_Overview.pdf

**Comment by ned-deily** [comment]
I believe that Apple started calling it just "OS X" starting with 10.7.  Since we support older releases yet, I think "Mac OS X" is fine for now.  I've tried to change all of the "Mac OSX" references to "Mac OS X" in the Download menus.  The changes don't show up in all places yet; it may be that they will take a bit to propagate.

**Comment by ned-deily** [comment]
The changes to the Download pop-ups have finally propagated through, at least for me.  Unless anyone has any other objections, I think this issue could be closed.

**Comment by hynek** [comment]
I was going to say that I’m not Apple’s CMO and it’s fine :), however there seems to be a problem with the new length:

![image](https://f.cloud.github.com/assets/41240/2240032/e8a33aca-9c6f-11e3-8bd7-cbe32aafacb4.png)

Happens in Chrome (35 + canary), but not Firefox or Safari.
