### ISSUE TITLE
Length limit on pyPi rst file processing

### ISSUE THREAD

**Issue by TonyFlury** [python/pythondotorg#836]
There appears to be a silent length limit imposed on the pyPi site when rst is used as the summary for a module. Content over a certain size although it is valid rst content, gets displayed as flat text.

This length limit does not seem to be documented anywhere.

**Comment by willingc** [comment]
@TonyFlury If I am reading your issue report correctly, your question is related to the PyPi packaging site and its handling of rst content. If you report your issue (or scan for it) in the PyPi issue tracker (https://bitbucket.org/pypa/pypi/issues), the PyPi team can provide you more meaningful responses.

This issue tracker is focused on the python.org website. Please let me know if you need any help following up with the PyPi team.

**Comment by berkerpeksag** [comment]
Also, PyPI uses https://github.com/pypa/readme, so you can check whether it's a bug or not on PyPI/readme.

Thanks for the report!

**Comment by TonyFlury** [comment]
Not entirely sure why this has been closed - are you expecting me to search for bugs in a downstream package which you use but I don't ?

**Comment by malemburg** [comment]
It was closed, because this is not the right tracker to report PyPI problems. PyPI's issue tracker can be found at: https://bitbucket.org/pypa/pypi/issues/ (as Carol already mentioned).

This ticket appears to be similar to what you are reporting: https://bitbucket.org/pypa/pypi/issues/161/rest-formatting-fails-and-there-is-no-way
