### ISSUE TITLE
Add some love to the code snippets on the pep pages

### ISSUE THREAD

**Issue by nwjlyons** [python/pythondotorg#889]
I'd like to see syntax highlighting via http://pygments.org/ or a frontend javascript library.

Also don't wrap code snippets on mobile.

```
pre.literal-block {
    white-space: pre;
    overflow-x: scroll;
    word-wrap: normal;
}
```

**Comment by berkerpeksag** [comment]
Thank you for the report. Our goal is to host all PEPs on RtD. You can see the list of remaining tasks at https://github.com/python/peps/projects/1 I'd like to spend more time on that project instead of adding features to the legacy importer in python.org (which would also increase the risk of introducing bugs in a stable software)
