### ISSUE TITLE
Developer guide is (about to become) out of date?

### ISSUE THREAD

**Issue by steveholden** [python/pythondotorg#895]
The page at https://docs.python.org/devguide/setup.html still discusses Mercurial. I'm aware that a decision was recently taken to migrate to git (GitHub?), but am currently unaware of the status of this move. Coordination with and input from the dev team will be required to ensure that would-be developers are directed to the right place.

**Comment by berkerpeksag** [comment]
The status (it may be a little outdated) of the move can be found in PEP 512: https://www.python.org/dev/peps/pep-0512/#status But I think it's too early to start updating the devguide since we haven't started to move any official Python repository (cpython, peps, devguide, benchmarks etc.) to Git yet. I propose some updates for the devguide on the core-workflow list for example.

Also, we usually use bugs.python.org for issues related to Python core development (there is a ["Devguide" component](http://bugs.python.org/issue?%40search_text=&ignore=file%3Acontent&title=&%40columns=title&id=&%40columns=id&stage=&creation=&creator=&activity=&%40columns=activity&%40sort=activity&actor=&nosy=&type=&components=26&versions=&dependencies=&assignee=&keywords=&priority=&status=1&%40columns=status&resolution=&nosy_count=&message_count=&%40group=&%40pagesize=50&%40startwith=0&%40sortdir=on&%40queryname=&%40old-queryname=&%40action=search) for this in bugs.python.org)
