### ISSUE TITLE
"Download Python for Other Platforms" out of date

### ISSUE THREAD

**Issue by pitrou** [python/pythondotorg#96]
The contents on this page are massively outdated ("Python 2.1 for AIX"? "PyAROS"?):
http://python.org/download/other/

**Comment by akuchling** [comment]
Good suggestion!  I've changed the Download > Others menu item to not be displayed any more.  It took a little while for the change to become visible (presumably a cache).

**Comment by birkenfeld** [comment]
I commented out platforms with very old versions (everything < 2.4) now.

**Comment by berkerpeksag** [comment]
* Python for BeOS: Links are broken
* Python for MorphOS: Latest Python 3 version is [3.2.2](http://yellowblue.free.fr/yiki/doku.php/en:dev:python:rel3x:start). According to [changelog](http://yellowblue.free.fr/yiki/doku.php/en:dev:python:rel3x:historic), it's not maintained since 2012.
* Python for MS-DOS: Latest Python version is 2.4
* Python for OS/2: Latest Python version is 2.4.4. There is a note at http://members.pcug.org.au/~andymac/python.html:

  > NOTE: I am no longer in a position to support any of my OS/2 ports or software. The software packages will stay available from this site for the time being but will be removed at some point in the future. 19Jan2017
* Python for OS/390 and z/OS: Latest Python version is 2.4.1
* Python for (what used to be Acorn) RISC OS: http://python.acorn.de/ is not online anymore
* Python for S60: Latest Python version is 2.5.4
* Python for Windows CE or Pocket PC: We already dropped Windows CE support

The up-to-date versions are Python for IBM i (2.7 and 3.4), Python for VMS (2.7.13, [changelog](http://www.vmspython.org/doku.php?id=history)), ActivePython (2.7 and 3.5, for HP-UX) I think we should keep these three and remove the ones I listed above.

**Comment by cclauss** [comment]
Python for OS/390 and z/OS should be http://www.rocketsoftware.com/zos-open-source

CPython for iOS needs to be added http://omz-software.com/pythonista/

**Comment by berkerpeksag** [comment]
I've now updated the list based on https://github.com/python/pythondotorg/issues/96#issuecomment-317228899 and https://github.com/python/pythondotorg/issues/96#issuecomment-324434068.
