### ISSUE TITLE
Can't Download Newer Versions of Python

### ISSUE THREAD

**Issue by SwiftlyGaming** [python/pythondotorg#973]
I've need to download python 3.5 and up but when i try, This pops up: One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file.

0x800700d - The data is invalid

But i can download the older versions 3.4.5 and older. As long as it is .msi
[Python 3.5.2 (64-bit)_20160725133658.txt](https://github.com/python/pythondotorg/files/382332/Python.3.5.2.64-bit._20160725133658.txt)

**Comment by berkerpeksag** [comment]
Thanks for the report, but this tracker is for issues with www.python.org. Issues with Windows installer need to be reported to https://bugs.python.org/ (since I'm not a Windows user I'm not sure if this is an actual bug in the Windows installer so you may want to upgrade to the latest service pack (if possible) before creating a new issue.)
