### ISSUE TITLE
Membership Dropdown

### ISSUE THREAD

**Issue by MarkMangoba** [python/pythondotorg#974]
Per @ejodlowska 

We need to remove sponsor members from this drop down and create a new drop down saying "Sponsor"

https://www.python.org/psf-landing/, the "Membership" dropdown

**Comment by ejodlowska** [comment]
@MarkMangoba @berkerpeksag The PSF no longer has Sponsor Members. Under the pydotorg 1st navigation of PSF and then under the 2nd navigation "Membership" (https://www.python.org/psf-landing/), there is a drop down called "Sponsor Membership". That needs to be removed from the "Membership" 2nd nav since the PSF no longer considers Sponsors as Members. Furthermore, we need to move what "Sponsor Membership" directed to (https://www.python.org/psf/sponsorship/) to it's own 2nd nav and have it be called "Sponsorship". Let me know if you need more details on this...I can always mock something up.

**Comment by berkerpeksag** [comment]
Hi Ewa, here is a screenshot of I'm planning to do:

![screenshot from 2016-08-04 12 13 50](https://cloud.githubusercontent.com/assets/26338/17396634/f54fb84c-5a3c-11e6-8d59-84a7c0f02539.png)
- Removed "Sponsor Membership" from "Membership" menu
- Added "Sponsorship" menu between "About" and "Membership"

Let me know if I didn't understand it correctly.

**Comment by ejodlowska** [comment]
@berkerpeksag This is exactly what I meant! Thank you for acting so quickly on this!

**Comment by MarkMangoba** [comment]
thanks @berkerpeksag.
